/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

#include "accessor.h"

#include "POUS.h"

// CONFIGURATION CONFIG0

void RES0_init__(void);

void config_init__(void) {
  BOOL retain;
  retain = 0;
  
  RES0_init__();
}

void RES0_run__(unsigned long tick, int iter);

void config_run__(unsigned long tick, int iter) {
  RES0_run__(tick, iter);
}

// only used for optee to end context
void RES0_end__(void);

void config_end__(void) {
  RES0_end__();
}
unsigned long long common_ticktime__ = 20000000ULL; /*ns*/
unsigned long greatest_tick_count__ = 0UL; /*tick*/
